[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "https://epademtaban.netlify.app/*"
  to = "https://tabanlik.epadem.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://epademtaban.netlify.app/*"
  to = "https://tabanlik.epadem.com/:splat"
  status = 301
  force = true
